server {
    listen 80;
    server_name asd-kontur.ru;

    location /.well-known/acme-challenge/ {
        root /var/www/certbot;
    }

    location / {
        return 301 https://$host$request_uri;
    }
}

server {
    listen 443 ssl;
    server_name asd-kontur.ru;

    ssl_certificate /etc/letsencrypt/live/asd-kontur.ru/fullchain.pem;
    ssl_certificate_key /etc/letsencrypt/live/asd-kontur.ru/privkey.pem;

    add_header X-Content-Type-Options "nosniff" always;
    add_header Referrer-Policy "strict-origin-when-cross-origin" always;
    add_header Content-Security-Policy "default-src 'self'; style-src 'self'; img-src 'self'; base-uri 'none'; form-action 'none'; frame-ancestors 'none'" always;

    root /var/www/asd-kontur;
    index index.html;

    location / {
        try_files $uri $uri/ =404;
    }
}
