"""SQLAlchemy Core metadata mirroring the deterministic Alembic baseline."""

from __future__ import annotations

import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

metadata = sa.MetaData()

organizations = sa.Table(
    "organizations",
    metadata,
    sa.Column("organization_id", postgresql.UUID(as_uuid=True), primary_key=True),
    sa.Column("display_name", sa.Text, nullable=False),
    sa.Column("external_id", sa.Text),
    sa.Column("status", sa.Text, nullable=False),
    sa.Column("revision", sa.BigInteger, nullable=False),
    sa.Column("retention_class", sa.Text, nullable=False),
    sa.Column("created_by_identity_id", sa.Text, nullable=False),
    sa.Column("correlation_id", postgresql.UUID(as_uuid=True), nullable=False),
    sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint("revision >= 1", name="ck_organization_revision_positive"),
    sa.CheckConstraint(
        "status IN ('active', 'suspended', 'closed')",
        name="ck_organization_status",
    ),
    schema="organization",
)

construction_objects = sa.Table(
    "construction_objects",
    metadata,
    sa.Column("organization_id", postgresql.UUID(as_uuid=True), primary_key=True),
    sa.Column("construction_object_id", postgresql.UUID(as_uuid=True), primary_key=True),
    sa.Column("display_name", sa.Text, nullable=False),
    sa.Column("external_id", sa.Text),
    sa.Column("status", sa.Text, nullable=False),
    sa.Column("revision", sa.BigInteger, nullable=False),
    sa.Column("retention_class", sa.Text, nullable=False),
    sa.Column("created_by_identity_id", sa.Text, nullable=False),
    sa.Column("correlation_id", postgresql.UUID(as_uuid=True), nullable=False),
    sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(
        ["organization_id"],
        ["organization.organizations.organization_id"],
        ondelete="RESTRICT",
        name="fk_construction_object_organization",
    ),
    sa.UniqueConstraint(
        "organization_id",
        "external_id",
        name="uq_construction_object_external_id",
    ),
    sa.CheckConstraint("revision >= 1", name="ck_construction_object_revision_positive"),
    schema="organization",
)

workspaces = sa.Table(
    "workspaces",
    metadata,
    sa.Column("organization_id", postgresql.UUID(as_uuid=True), primary_key=True),
    sa.Column("workspace_id", postgresql.UUID(as_uuid=True), primary_key=True),
    sa.Column("construction_object_id", postgresql.UUID(as_uuid=True), nullable=False),
    sa.Column("lifecycle_state", sa.Text, nullable=False),
    sa.Column("lifecycle_version", sa.BigInteger, nullable=False),
    sa.Column("workspace_revision", sa.BigInteger, nullable=False),
    sa.Column("write_fenced", sa.Boolean, nullable=False),
    sa.Column("legal_hold_active", sa.Boolean, nullable=False),
    sa.Column("purge_started_at", sa.DateTime(timezone=True)),
    sa.Column("destroyed_at", sa.DateTime(timezone=True)),
    sa.Column("revision", sa.BigInteger, nullable=False),
    sa.Column("retention_class", sa.Text, nullable=False),
    sa.Column("retention_profile_key", sa.Text, nullable=False),
    sa.Column("retention_profile_version", sa.Text, nullable=False),
    sa.Column("policy_assignment_key", sa.Text, nullable=False),
    sa.Column("policy_assignment_version", sa.Text, nullable=False),
    sa.Column("rule_set_key", sa.Text, nullable=False),
    sa.Column("rule_set_version", sa.Text, nullable=False),
    sa.Column("contract_registry_version", sa.Text, nullable=False),
    sa.Column("created_by_identity_id", sa.Text, nullable=False),
    sa.Column("correlation_id", postgresql.UUID(as_uuid=True), nullable=False),
    sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(
        ["organization_id", "construction_object_id"],
        [
            "organization.construction_objects.organization_id",
            "organization.construction_objects.construction_object_id",
        ],
        ondelete="RESTRICT",
        name="fk_workspace_construction_object",
    ),
    sa.CheckConstraint("revision >= 1", name="ck_workspace_revision_positive"),
    sa.CheckConstraint(
        "lifecycle_state IN "
        "('PROVISIONING','ACTIVE','FREEZING','FROZEN','FINALIZING','FINALIZED',"
        "'EXPORTING','EXPORTED','ARCHIVING','ARCHIVED','CLOSED','REOPENING',"
        "'RESET_PLANNING','RESET_AUTHORIZED','PURGING','VERIFYING_RESET',"
        "'RESET_VERIFIED','DESTROYING','DESTROYED','RECOVERY_REQUIRED','QUARANTINED')",
        name="ck_workspace_lifecycle_state",
    ),
    sa.CheckConstraint(
        "lower(retention_profile_version) <> 'latest' AND "
        "lower(policy_assignment_version) <> 'latest' AND "
        "lower(rule_set_version) <> 'latest' AND "
        "lower(contract_registry_version) <> 'latest'",
        name="ck_workspace_exact_versions",
    ),
    schema="workspace",
)

workspace_revisions = sa.Table(
    "workspace_revisions",
    metadata,
    sa.Column("organization_id", postgresql.UUID(as_uuid=True), primary_key=True),
    sa.Column("workspace_id", postgresql.UUID(as_uuid=True), primary_key=True),
    sa.Column("revision", sa.BigInteger, primary_key=True),
    sa.Column("workspace_version_id", postgresql.UUID(as_uuid=True), nullable=False),
    sa.Column("lifecycle_state", sa.Text, nullable=False),
    sa.Column("reason_code", sa.Text, nullable=False),
    sa.Column("retention_profile_key", sa.Text, nullable=False),
    sa.Column("retention_profile_version", sa.Text, nullable=False),
    sa.Column("policy_assignment_key", sa.Text, nullable=False),
    sa.Column("policy_assignment_version", sa.Text, nullable=False),
    sa.Column("rule_set_key", sa.Text, nullable=False),
    sa.Column("rule_set_version", sa.Text, nullable=False),
    sa.Column("contract_registry_version", sa.Text, nullable=False),
    sa.Column("inventory_fingerprint", sa.Text),
    sa.Column("created_by_identity_id", sa.Text, nullable=False),
    sa.Column("correlation_id", postgresql.UUID(as_uuid=True), nullable=False),
    sa.Column("causation_id", postgresql.UUID(as_uuid=True)),
    sa.Column("recorded_at", sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(
        ["organization_id", "workspace_id"],
        ["workspace.workspaces.organization_id", "workspace.workspaces.workspace_id"],
        ondelete="RESTRICT",
        name="fk_workspace_revision_workspace",
    ),
    sa.UniqueConstraint("workspace_version_id", name="uq_workspace_version_id"),
    sa.CheckConstraint("revision >= 1", name="ck_workspace_version_revision_positive"),
    schema="workspace",
)

mode_executions = sa.Table(
    "mode_executions",
    metadata,
    sa.Column("organization_id", postgresql.UUID(as_uuid=True), primary_key=True),
    sa.Column("workspace_id", postgresql.UUID(as_uuid=True), primary_key=True),
    sa.Column("mode_execution_id", postgresql.UUID(as_uuid=True), primary_key=True),
    sa.Column("mode", sa.Text, nullable=False),
    sa.Column("purpose", sa.Text, nullable=False),
    sa.Column("state", sa.Text, nullable=False),
    sa.Column("revision", sa.BigInteger, nullable=False),
    sa.Column("input_manifest_ref", sa.Text, nullable=False),
    sa.Column("contract_key", sa.Text, nullable=False),
    sa.Column("contract_version", sa.Text, nullable=False),
    sa.Column("schema_id", sa.Text, nullable=False),
    sa.Column("schema_version", sa.Text, nullable=False),
    sa.Column("process_definition_key", sa.Text, nullable=False),
    sa.Column("process_definition_version", sa.Text, nullable=False),
    sa.Column("authority_profile_key", sa.Text, nullable=False),
    sa.Column("authority_profile_version", sa.Text, nullable=False),
    sa.Column("output_contract_key", sa.Text, nullable=False),
    sa.Column("output_contract_version", sa.Text, nullable=False),
    sa.Column("policy_assignment_key", sa.Text, nullable=False),
    sa.Column("policy_assignment_version", sa.Text, nullable=False),
    sa.Column("rule_set_key", sa.Text, nullable=False),
    sa.Column("rule_set_version", sa.Text, nullable=False),
    sa.Column("retention_class", sa.Text, nullable=False),
    sa.Column("created_by_identity_id", sa.Text, nullable=False),
    sa.Column("correlation_id", postgresql.UUID(as_uuid=True), nullable=False),
    sa.Column("causation_id", postgresql.UUID(as_uuid=True)),
    sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
    sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(
        ["organization_id", "workspace_id"],
        ["workspace.workspaces.organization_id", "workspace.workspaces.workspace_id"],
        ondelete="RESTRICT",
        name="fk_mode_execution_workspace",
    ),
    sa.CheckConstraint(
        "mode IN ('Tender', 'Support', 'Audit', 'Restoration')",
        name="ck_mode_execution_mode",
    ),
    sa.CheckConstraint("revision >= 1", name="ck_mode_execution_revision_positive"),
    sa.CheckConstraint(
        "lower(contract_version) <> 'latest' AND lower(schema_version) <> 'latest' "
        "AND lower(policy_assignment_version) <> 'latest' "
        "AND lower(rule_set_version) <> 'latest'",
        name="ck_mode_execution_exact_versions",
    ),
    schema="workspace",
)

workspace_objects = sa.Table(
    "objects",
    metadata,
    sa.Column("organization_id", postgresql.UUID(as_uuid=True), primary_key=True),
    sa.Column("workspace_id", postgresql.UUID(as_uuid=True), primary_key=True),
    sa.Column("object_id", postgresql.UUID(as_uuid=True), primary_key=True),
    sa.Column("object_version", sa.BigInteger, nullable=False),
    sa.Column("object_class", sa.Text, nullable=False),
    sa.Column("content_digest", sa.Text, nullable=False),
    sa.Column("size_bytes", sa.BigInteger, nullable=False),
    sa.Column("media_type", sa.Text, nullable=False),
    sa.Column("storage_adapter_key", sa.Text, nullable=False),
    sa.Column("storage_receipt_ref", sa.Text, nullable=False),
    sa.Column("access_capability_ref", sa.Text, nullable=False),
    sa.Column("classification", sa.Text, nullable=False),
    sa.Column("retention_class", sa.Text, nullable=False),
    sa.Column("created_by_identity_id", sa.Text, nullable=False),
    sa.Column("correlation_id", postgresql.UUID(as_uuid=True), nullable=False),
    sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(
        ["organization_id", "workspace_id"],
        ["workspace.workspaces.organization_id", "workspace.workspaces.workspace_id"],
        ondelete="RESTRICT",
        name="fk_workspace_object_workspace",
    ),
    sa.UniqueConstraint(
        "organization_id",
        "workspace_id",
        "object_id",
        "object_version",
        name="uq_workspace_object_version",
    ),
    sa.CheckConstraint("object_version >= 1", name="ck_workspace_object_version_positive"),
    sa.CheckConstraint("size_bytes >= 0", name="ck_workspace_object_size_nonnegative"),
    sa.CheckConstraint(
        "content_digest ~ '^sha256:[a-f0-9]{64}$'",
        name="ck_workspace_object_digest",
    ),
    schema="workspace",
)

object_links = sa.Table(
    "object_links",
    metadata,
    sa.Column("organization_id", postgresql.UUID(as_uuid=True), primary_key=True),
    sa.Column("workspace_id", postgresql.UUID(as_uuid=True), primary_key=True),
    sa.Column("link_id", postgresql.UUID(as_uuid=True), primary_key=True),
    sa.Column("source_object_id", postgresql.UUID(as_uuid=True), nullable=False),
    sa.Column("target_object_id", postgresql.UUID(as_uuid=True), nullable=False),
    sa.Column("relation_kind", sa.Text, nullable=False),
    sa.Column("created_by_identity_id", sa.Text, nullable=False),
    sa.Column("correlation_id", postgresql.UUID(as_uuid=True), nullable=False),
    sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(
        ["organization_id", "workspace_id", "source_object_id"],
        [
            "workspace.objects.organization_id",
            "workspace.objects.workspace_id",
            "workspace.objects.object_id",
        ],
        ondelete="RESTRICT",
        name="fk_object_link_source_same_workspace",
    ),
    sa.ForeignKeyConstraint(
        ["organization_id", "workspace_id", "target_object_id"],
        [
            "workspace.objects.organization_id",
            "workspace.objects.workspace_id",
            "workspace.objects.object_id",
        ],
        ondelete="RESTRICT",
        name="fk_object_link_target_same_workspace",
    ),
    schema="workspace",
)

workspace_audit_records = sa.Table(
    "workspace_records",
    metadata,
    sa.Column("organization_id", postgresql.UUID(as_uuid=True), primary_key=True),
    sa.Column("workspace_id", postgresql.UUID(as_uuid=True), primary_key=True),
    sa.Column("audit_record_id", postgresql.UUID(as_uuid=True), primary_key=True),
    sa.Column("audit_version", sa.Integer, nullable=False),
    sa.Column("recorded_at", sa.DateTime(timezone=True), nullable=False),
    sa.Column("actor_identity_id", sa.Text),
    sa.Column("service_identity_id", sa.Text),
    sa.Column("capability", sa.Text, nullable=False),
    sa.Column("operation", sa.Text, nullable=False),
    sa.Column("outcome_code", sa.Text, nullable=False),
    sa.Column("contract_key", sa.Text, nullable=False),
    sa.Column("contract_version", sa.Text, nullable=False),
    sa.Column("policy_key", sa.Text, nullable=False),
    sa.Column("policy_version", sa.Text, nullable=False),
    sa.Column("correlation_id", postgresql.UUID(as_uuid=True), nullable=False),
    sa.Column("causation_id", postgresql.UUID(as_uuid=True)),
    sa.Column("safe_message_key", sa.Text, nullable=False),
    sa.Column("diagnostic_reference", sa.Text),
    sa.Column("retention_class", sa.Text, nullable=False),
    sa.Column("record_digest", sa.Text, nullable=False),
    sa.ForeignKeyConstraint(
        ["organization_id", "workspace_id"],
        ["workspace.workspaces.organization_id", "workspace.workspaces.workspace_id"],
        ondelete="RESTRICT",
        name="fk_audit_workspace",
    ),
    sa.CheckConstraint(
        "actor_identity_id IS NOT NULL OR service_identity_id IS NOT NULL",
        name="ck_audit_actor_or_service",
    ),
    sa.CheckConstraint("lower(contract_version) <> 'latest'", name="ck_audit_contract_exact"),
    sa.CheckConstraint("lower(policy_version) <> 'latest'", name="ck_audit_policy_exact"),
    schema="audit",
)

outbox_records = sa.Table(
    "workspace_outbox",
    metadata,
    sa.Column("organization_id", postgresql.UUID(as_uuid=True), primary_key=True),
    sa.Column("workspace_id", postgresql.UUID(as_uuid=True), primary_key=True),
    sa.Column("outbox_record_id", postgresql.UUID(as_uuid=True), primary_key=True),
    sa.Column("event_id", postgresql.UUID(as_uuid=True), nullable=False),
    sa.Column("aggregate_id", postgresql.UUID(as_uuid=True), nullable=False),
    sa.Column("aggregate_version", sa.BigInteger, nullable=False),
    sa.Column("destination", sa.Text, nullable=False),
    sa.Column("state", sa.Text, nullable=False),
    sa.Column("attempt_count", sa.Integer, nullable=False),
    sa.Column("contract_key", sa.Text, nullable=False),
    sa.Column("contract_version", sa.Text, nullable=False),
    sa.Column("schema_id", sa.Text, nullable=False),
    sa.Column("schema_version", sa.Text, nullable=False),
    sa.Column("payload", postgresql.JSONB, nullable=False),
    sa.Column("payload_digest", sa.Text, nullable=False),
    sa.Column("retention_class", sa.Text, nullable=False),
    sa.Column("correlation_id", postgresql.UUID(as_uuid=True), nullable=False),
    sa.Column("causation_id", postgresql.UUID(as_uuid=True)),
    sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(
        ["organization_id", "workspace_id"],
        ["workspace.workspaces.organization_id", "workspace.workspaces.workspace_id"],
        ondelete="RESTRICT",
        name="fk_outbox_workspace",
    ),
    sa.UniqueConstraint("organization_id", "workspace_id", "event_id", name="uq_outbox_event"),
    sa.CheckConstraint("attempt_count >= 0", name="ck_outbox_attempt_nonnegative"),
    sa.CheckConstraint(
        "lower(contract_version) <> 'latest' AND lower(schema_version) <> 'latest'",
        name="ck_outbox_exact_versions",
    ),
    schema="messaging",
)

inbox_receipts = sa.Table(
    "workspace_inbox_receipts",
    metadata,
    sa.Column("organization_id", postgresql.UUID(as_uuid=True), primary_key=True),
    sa.Column("workspace_id", postgresql.UUID(as_uuid=True), primary_key=True),
    sa.Column("consumer_key", sa.Text, primary_key=True),
    sa.Column("message_id", postgresql.UUID(as_uuid=True), primary_key=True),
    sa.Column("payload_digest", sa.Text, nullable=False),
    sa.Column("outcome", sa.Text, nullable=False),
    sa.Column("attempt_count", sa.Integer, nullable=False),
    sa.Column("contract_key", sa.Text, nullable=False),
    sa.Column("contract_version", sa.Text, nullable=False),
    sa.Column("schema_id", sa.Text, nullable=False),
    sa.Column("schema_version", sa.Text, nullable=False),
    sa.Column("correlation_id", postgresql.UUID(as_uuid=True), nullable=False),
    sa.Column("received_at", sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(
        ["organization_id", "workspace_id"],
        ["workspace.workspaces.organization_id", "workspace.workspaces.workspace_id"],
        ondelete="RESTRICT",
        name="fk_inbox_workspace",
    ),
    sa.CheckConstraint("attempt_count >= 1", name="ck_inbox_attempt_positive"),
    schema="messaging",
)

idempotency_records = sa.Table(
    "workspace_idempotency",
    metadata,
    sa.Column("organization_id", postgresql.UUID(as_uuid=True), primary_key=True),
    sa.Column("workspace_id", postgresql.UUID(as_uuid=True), primary_key=True),
    sa.Column("handler_key", sa.Text, primary_key=True),
    sa.Column("idempotency_key", sa.Text, primary_key=True),
    sa.Column("semantic_digest", sa.Text, nullable=False),
    sa.Column("command_id", postgresql.UUID(as_uuid=True), nullable=False),
    sa.Column("state", sa.Text, nullable=False),
    sa.Column("outcome_ref", sa.Text),
    sa.Column("correlation_id", postgresql.UUID(as_uuid=True), nullable=False),
    sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
    sa.Column("completed_at", sa.DateTime(timezone=True)),
    sa.ForeignKeyConstraint(
        ["organization_id", "workspace_id"],
        ["workspace.workspaces.organization_id", "workspace.workspaces.workspace_id"],
        ondelete="RESTRICT",
        name="fk_idempotency_workspace",
    ),
    schema="messaging",
)
