"""Stable failures for the common domain process kernel."""

from __future__ import annotations

from enum import StrEnum


class KernelErrorCode(StrEnum):
    CANDIDATE_NOT_VALIDATED = "KERNEL.CANDIDATE_NOT_VALIDATED"
    EVIDENCE_MISSING = "KERNEL.EVIDENCE_MISSING"
    AUTHORITY_DENIED = "KERNEL.AUTHORITY_DENIED"
    AUTO_CONFIRM_DENIED = "KERNEL.AUTO_CONFIRM_DENIED"
    PROFESSIONAL_AUTHORITY_REQUIRED = "KERNEL.PROFESSIONAL_AUTHORITY_REQUIRED"
    CONFLICT_UNRESOLVED = "KERNEL.CONFLICT_UNRESOLVED"
    UNCERTAINTY_UNRESOLVED = "KERNEL.UNCERTAINTY_UNRESOLVED"
    RULE_NOT_ACTIVE = "KERNEL.RULE_NOT_ACTIVE"
    RULESET_NOT_PINNED = "KERNEL.RULESET_NOT_PINNED"
    CONCURRENCY_CONFLICT = "KERNEL.CONCURRENCY_CONFLICT"
    IDEMPOTENCY_CONFLICT = "KERNEL.IDEMPOTENCY_CONFLICT"
    WORKSPACE_FENCED = "KERNEL.WORKSPACE_FENCED"
    SCOPE_VIOLATION = "KERNEL.SCOPE_VIOLATION"
    INVALID_QUANTITY = "KERNEL.INVALID_QUANTITY"
    DEPENDENCY_CYCLE = "KERNEL.DEPENDENCY_CYCLE"
    INDETERMINATE = "KERNEL.INDETERMINATE"


class KernelError(RuntimeError):
    def __init__(self, code: KernelErrorCode, safe_message: str) -> None:
        self.code = code
        self.safe_message = safe_message
        super().__init__(f"{code}: {safe_message}")
