"""Workspace lifecycle foundation shared by Tender, Support, Audit, and Restoration."""

from .destruction import DestructionCoordinator, PurgeOutcome, RegistrySnapshot
from .errors import LifecycleError, LifecycleErrorCode
from .models import (
    AdapterHealth,
    AdapterOutcome,
    AdapterReceipt,
    AssuranceClass,
    Authority,
    Basis,
    DeletionItem,
    DeletionPlan,
    DestructionAttestation,
    DestructiveAuthorization,
    ExactVersionReference,
    InventoryItem,
    LifecycleState,
    Mode,
    ModeExecutionConfiguration,
    RecoveryCheckpoint,
    ResidualScan,
    RetentionProfile,
    StorageAdapterDefinition,
    VerificationOutcome,
)
from .operations import (
    ArchiveImportDecision,
    ArchiveImportGuard,
    FinalizationDecision,
    FinalizationGuard,
    FreezeAssessment,
    ProvisioningDecision,
    ProvisioningGuard,
    reopen_allowed,
)
from .postgres import PostgresLifecycleRepository, PostgresWorkspaceStorageAdapter
from .state_machine import LifecycleStateMachine, TransitionDecision
from .storage import (
    ArchiveEntry,
    ArchiveReceipt,
    ContainedFilesystemAdapter,
    InMemoryStorageAdapter,
    PortableArchiveService,
    StorageAdapter,
    inventory_digest,
)

__all__ = [
    "AdapterHealth",
    "AdapterOutcome",
    "AdapterReceipt",
    "ArchiveEntry",
    "ArchiveImportDecision",
    "ArchiveImportGuard",
    "ArchiveReceipt",
    "AssuranceClass",
    "Authority",
    "Basis",
    "ContainedFilesystemAdapter",
    "DeletionItem",
    "DeletionPlan",
    "DestructionAttestation",
    "DestructionCoordinator",
    "DestructiveAuthorization",
    "ExactVersionReference",
    "FinalizationDecision",
    "FinalizationGuard",
    "FreezeAssessment",
    "InMemoryStorageAdapter",
    "InventoryItem",
    "LifecycleError",
    "LifecycleErrorCode",
    "LifecycleState",
    "LifecycleStateMachine",
    "Mode",
    "ModeExecutionConfiguration",
    "PortableArchiveService",
    "PostgresLifecycleRepository",
    "PostgresWorkspaceStorageAdapter",
    "ProvisioningDecision",
    "ProvisioningGuard",
    "PurgeOutcome",
    "RecoveryCheckpoint",
    "RegistrySnapshot",
    "ResidualScan",
    "RetentionProfile",
    "StorageAdapter",
    "StorageAdapterDefinition",
    "TransitionDecision",
    "VerificationOutcome",
    "inventory_digest",
    "reopen_allowed",
]
