/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/v1/capabilities": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Capabilities */
        get: operations["capabilities_api_v1_capabilities_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/health/live": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Live */
        get: operations["live_api_v1_health_live_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/health/ready": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Ready */
        get: operations["ready_api_v1_health_ready_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/platform/knowledge-status": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Knowledge Status */
        get: operations["knowledge_status_api_v1_platform_knowledge_status_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/session": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Session Info */
        get: operations["session_info_api_v1_session_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/session/login": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Login */
        post: operations["login_api_v1_session_login_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/session/logout": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Logout */
        post: operations["logout_api_v1_session_logout_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/session/rotate": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Rotate */
        post: operations["rotate_api_v1_session_rotate_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/workspaces": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Workspaces */
        get: operations["list_workspaces_api_v1_workspaces_get"];
        put?: never;
        /** Create Workspace */
        post: operations["create_workspace_api_v1_workspaces_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/workspaces/{workspace_id}/documents": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Documents */
        get: operations["list_documents_api_v1_workspaces__workspace_id__documents_get"];
        put?: never;
        /** Upload Documents */
        post: operations["upload_documents_api_v1_workspaces__workspace_id__documents_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/workspaces/{workspace_id}/documents/{document_id}/content": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Document Content */
        get: operations["document_content_api_v1_workspaces__workspace_id__documents__document_id__content_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/workspaces/{workspace_id}/events": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Events */
        get: operations["events_api_v1_workspaces__workspace_id__events_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/workspaces/{workspace_id}/evidence/{document_id}/pages/{page_number}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Evidence */
        get: operations["evidence_api_v1_workspaces__workspace_id__evidence__document_id__pages__page_number__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/workspaces/{workspace_id}/jobs": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Jobs */
        get: operations["jobs_api_v1_workspaces__workspace_id__jobs_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/workspaces/{workspace_id}/jobs/{job_id}/cancel": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Cancel Job */
        post: operations["cancel_job_api_v1_workspaces__workspace_id__jobs__job_id__cancel_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/workspaces/{workspace_id}/lifecycle": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Lifecycle */
        get: operations["lifecycle_api_v1_workspaces__workspace_id__lifecycle_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/workspaces/{workspace_id}/lifecycle/reset/execute": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Execute Workspace Reset */
        post: operations["execute_workspace_reset_api_v1_workspaces__workspace_id__lifecycle_reset_execute_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/workspaces/{workspace_id}/lifecycle/reset/prepare": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Prepare Workspace Reset */
        post: operations["prepare_workspace_reset_api_v1_workspaces__workspace_id__lifecycle_reset_prepare_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/workspaces/{workspace_id}/modes/{mode}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Mode View */
        get: operations["mode_view_api_v1_workspaces__workspace_id__modes__mode__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** Body_upload_documents_api_v1_workspaces__workspace_id__documents_post */
        Body_upload_documents_api_v1_workspaces__workspace_id__documents_post: {
            /** Files */
            files: string[];
            /** Relative Paths */
            relative_paths?: string | null;
        };
        /** CapabilityStatusView */
        CapabilityStatusView: {
            /** Blockers */
            blockers: string[];
            /** Contract Version */
            contract_version: string;
            /** Implemented */
            implemented: string[];
            /** Oks Ready */
            oks_ready: boolean;
            /** Product Ready */
            product_ready: boolean;
            /** Slice */
            slice: string;
            /** Trial Ready */
            trial_ready: boolean;
        };
        /** DocumentPage */
        DocumentPage: {
            /** Items */
            items: components["schemas"]["DocumentView"][];
            /** Next Cursor */
            next_cursor: string | null;
        };
        /** DocumentView */
        DocumentView: {
            /** Admission Status */
            admission_status: string;
            /** Capability Gaps */
            capability_gaps: string[];
            /** Content Digest */
            content_digest: string;
            /**
             * Document Id
             * Format: uuid
             */
            document_id: string;
            /** Extraction Status */
            extraction_status: string;
            /** Job Ids */
            job_ids: string[];
            /** Media Type */
            media_type: string;
            /**
             * Organization Id
             * Format: uuid
             */
            organization_id: string;
            /** Page Count */
            page_count: number | null;
            /** Prior Versions */
            prior_versions: number[];
            /**
             * Recorded At
             * Format: date-time
             */
            recorded_at: string;
            /** Relative Path */
            relative_path: string;
            /** Safe Display Name */
            safe_display_name: string;
            /** Size Bytes */
            size_bytes: number;
            /** Source Artifact Id */
            source_artifact_id: string | null;
            /** Source Version Id */
            source_version_id: string | null;
            /** Version */
            version: number;
            /**
             * Workspace Id
             * Format: uuid
             */
            workspace_id: string;
        };
        /** EvidenceLocatorView */
        EvidenceLocatorView: {
            /**
             * Document Id
             * Format: uuid
             */
            document_id: string;
            /** Document Version */
            document_version: number;
            /** Evidence Digest */
            evidence_digest: string;
            /** Extraction Method */
            extraction_method: string;
            /** Height Points */
            height_points: number;
            /** Page Number */
            page_number: number;
            /** Region */
            region: [
                number,
                number,
                number,
                number
            ];
            /** Rotation Degrees */
            rotation_degrees: number;
            /**
             * Source Locator Id
             * Format: uuid
             */
            source_locator_id: string;
            /**
             * Source Version Id
             * Format: uuid
             */
            source_version_id: string;
            /** Width Points */
            width_points: number;
        };
        /** EvidencePanelView */
        EvidencePanelView: {
            /** Authority Type */
            authority_type: string;
            /** Candidate Fact Status */
            candidate_fact_status: string;
            /** Conflicts */
            conflicts: string[];
            locator: components["schemas"]["EvidenceLocatorView"];
            /** Normative Edition */
            normative_edition: string | null;
            /** Practice Release */
            practice_release: string | null;
            /** Quarantined */
            quarantined: boolean;
            /** Rule Version */
            rule_version: string | null;
            /** Uncertainty */
            uncertainty: string[];
        };
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /** HealthView */
        HealthView: {
            /** Checks */
            checks?: {
                [key: string]: string;
            };
            /**
             * Status
             * @enum {string}
             */
            status: "live" | "ready" | "not_ready";
        };
        /** JobCancellationRequest */
        JobCancellationRequest: {
            /**
             * Confirmation
             * @constant
             */
            confirmation: "CANCEL_JOB";
        };
        /** JobView */
        JobView: {
            /** Attempt Count */
            attempt_count: number;
            /** Cancellation State */
            cancellation_state: string;
            /** Completed At */
            completed_at: string | null;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /** Heartbeat At */
            heartbeat_at: string | null;
            /**
             * Job Id
             * Format: uuid
             */
            job_id: string;
            /** Job Kind */
            job_kind: string;
            /** Max Attempts */
            max_attempts: number;
            /**
             * Organization Id
             * Format: uuid
             */
            organization_id: string;
            /** Priority */
            priority: number;
            /** Started At */
            started_at: string | null;
            /** State */
            state: string;
            /** Terminal Receipt Id */
            terminal_receipt_id: string | null;
            /** Typed Failure Code */
            typed_failure_code: string | null;
            /**
             * Workspace Id
             * Format: uuid
             */
            workspace_id: string;
        };
        /** KnowledgeStatusView */
        KnowledgeStatusView: {
            /** Active Gap Count */
            active_gap_count: number;
            /** Active Intelligence Count */
            active_intelligence_count: number;
            /** Active Playbook Count */
            active_playbook_count: number;
            /** Active Practice Release Count */
            active_practice_release_count: number;
            /** Blockers */
            blockers: string[];
            /** Conflict Count */
            conflict_count: number;
            /** Knowledge Ready */
            knowledge_ready: boolean;
            /** Last Verified Backup At */
            last_verified_backup_at: string | null;
            /** Memory Data Defect */
            memory_data_defect: boolean;
            /** Normative Identity Count */
            normative_identity_count: number;
            /** Practice Edition Count */
            practice_edition_count: number;
            /** Practice Guide Count */
            practice_guide_count: number;
            /** Projection States */
            projection_states: {
                [key: string]: unknown;
            };
            /** Quarantine Count */
            quarantine_count: number;
            /** Rule Version Count */
            rule_version_count: number;
            /** Semantic Fingerprints */
            semantic_fingerprints: {
                [key: string]: unknown;
            };
            /** Source Guidance Count */
            source_guidance_count: number;
            /** Verified Normative Edition Count */
            verified_normative_edition_count: number;
            /** Verified Normative Provision Count */
            verified_normative_provision_count: number;
        };
        /** LoginRequest */
        LoginRequest: {
            /** Password */
            password: string;
            /** Username */
            username: string;
        };
        /**
         * ModeName
         * @enum {string}
         */
        ModeName: "Tender" | "Support" | "Audit" | "Restoration";
        /** ModeView */
        ModeView: {
            /** Available Inputs */
            available_inputs: string[];
            /** Bounded Results */
            bounded_results: {
                [key: string]: unknown;
            };
            /** Execution Id */
            execution_id: string | null;
            /** Execution State */
            execution_state: string | null;
            /** Gaps */
            gaps: string[];
            /** Matrix Version Id */
            matrix_version_id: string | null;
            /** Missing Capabilities */
            missing_capabilities: string[];
            /** Mode */
            mode: string;
            /** Purpose */
            purpose: string;
            /** Readiness */
            readiness: string;
        };
        /** ResetChallengeView */
        ResetChallengeView: {
            /**
             * Assurance Profile
             * @constant
             */
            assurance_profile: "development_single_owner_confirmation";
            /**
             * Challenge Id
             * Format: uuid
             */
            challenge_id: string;
            /** Confirmation Text */
            confirmation_text: string;
            /**
             * Expires At
             * Format: date-time
             */
            expires_at: string;
            /** Target Lifecycle Version */
            target_lifecycle_version: number;
            /**
             * Workspace Id
             * Format: uuid
             */
            workspace_id: string;
        };
        /** ResetExecuteRequest */
        ResetExecuteRequest: {
            /**
             * Challenge Id
             * Format: uuid
             */
            challenge_id: string;
            /** Confirmation Text */
            confirmation_text: string;
        };
        /** ResetPrepareRequest */
        ResetPrepareRequest: {
            /**
             * Confirmation
             * @constant
             */
            confirmation: "PREPARE_WORKSPACE_RESET";
        };
        /** ResetReceiptView */
        ResetReceiptView: {
            /** Archive Package Digest */
            archive_package_digest: string;
            /**
             * Completed At
             * Format: date-time
             */
            completed_at: string;
            /** Deleted Object Count */
            deleted_object_count: number;
            /** Deleted Relation Row Count */
            deleted_relation_row_count: number;
            /**
             * Outcome
             * @enum {string}
             */
            outcome: "verified" | "reconciliation_required";
            /** Platform Fingerprint After */
            platform_fingerprint_after: string;
            /** Platform Fingerprint Before */
            platform_fingerprint_before: string;
            /**
             * Reset Receipt Id
             * Format: uuid
             */
            reset_receipt_id: string;
            /**
             * Workspace Id
             * Format: uuid
             */
            workspace_id: string;
        };
        /** SessionView */
        SessionView: {
            /**
             * Absolute Expires At
             * Format: date-time
             */
            absolute_expires_at: string;
            /** Owner Identity Id */
            owner_identity_id: string;
            /** Profile */
            profile: string;
            /** Username */
            username: string;
        };
        /** UploadBatchView */
        UploadBatchView: {
            /** Accepted Document Ids */
            accepted_document_ids: string[];
            /** Duplicate Document Ids */
            duplicate_document_ids: string[];
            /**
             * Intake Manifest Id
             * Format: uuid
             */
            intake_manifest_id: string;
            /** Job Ids */
            job_ids: string[];
            /** Manifest Digest */
            manifest_digest: string;
            /** Rejected Count */
            rejected_count: number;
        };
        /** ValidationError */
        ValidationError: {
            /** Context */
            ctx?: Record<string, never>;
            /** Input */
            input?: unknown;
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
        };
        /** WorkspaceCreate */
        WorkspaceCreate: {
            /** Display Name */
            display_name: string;
        };
        /** WorkspaceView */
        WorkspaceView: {
            /**
             * Construction Object Id
             * Format: uuid
             */
            construction_object_id: string;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /** Display Name */
            display_name: string;
            /** Lifecycle State */
            lifecycle_state: string;
            /** Lifecycle Version */
            lifecycle_version: number;
            /**
             * Organization Id
             * Format: uuid
             */
            organization_id: string;
            /**
             * Workspace Id
             * Format: uuid
             */
            workspace_id: string;
            /** Workspace Revision */
            workspace_revision: number;
            /** Write Fenced */
            write_fenced: boolean;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    capabilities_api_v1_capabilities_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CapabilityStatusView"];
                };
            };
        };
    };
    live_api_v1_health_live_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HealthView"];
                };
            };
        };
    };
    ready_api_v1_health_ready_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HealthView"];
                };
            };
        };
    };
    knowledge_status_api_v1_platform_knowledge_status_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["KnowledgeStatusView"];
                };
            };
        };
    };
    session_info_api_v1_session_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SessionView"];
                };
            };
        };
    };
    login_api_v1_session_login_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["LoginRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SessionView"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    logout_api_v1_session_logout_post: {
        parameters: {
            query?: never;
            header?: {
                "X-CSRF-Token"?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    rotate_api_v1_session_rotate_post: {
        parameters: {
            query?: never;
            header?: {
                "X-CSRF-Token"?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SessionView"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_workspaces_api_v1_workspaces_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["WorkspaceView"][];
                };
            };
        };
    };
    create_workspace_api_v1_workspaces_post: {
        parameters: {
            query?: never;
            header?: {
                "X-CSRF-Token"?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["WorkspaceCreate"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["WorkspaceView"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_documents_api_v1_workspaces__workspace_id__documents_get: {
        parameters: {
            query?: {
                limit?: number;
                cursor?: string | null;
                media_type?: string | null;
                processing_status?: string | null;
                sort?: string;
            };
            header?: never;
            path: {
                workspace_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DocumentPage"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    upload_documents_api_v1_workspaces__workspace_id__documents_post: {
        parameters: {
            query?: never;
            header?: {
                "X-CSRF-Token"?: string | null;
            };
            path: {
                workspace_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "multipart/form-data": components["schemas"]["Body_upload_documents_api_v1_workspaces__workspace_id__documents_post"];
            };
        };
        responses: {
            /** @description Successful Response */
            202: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UploadBatchView"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    document_content_api_v1_workspaces__workspace_id__documents__document_id__content_get: {
        parameters: {
            query?: never;
            header?: {
                Range?: string | null;
            };
            path: {
                workspace_id: string;
                document_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    events_api_v1_workspaces__workspace_id__events_get: {
        parameters: {
            query?: never;
            header?: {
                "Last-Event-ID"?: string | null;
            };
            path: {
                workspace_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    evidence_api_v1_workspaces__workspace_id__evidence__document_id__pages__page_number__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                workspace_id: string;
                document_id: string;
                page_number: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["EvidencePanelView"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    jobs_api_v1_workspaces__workspace_id__jobs_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                workspace_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["JobView"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    cancel_job_api_v1_workspaces__workspace_id__jobs__job_id__cancel_post: {
        parameters: {
            query?: never;
            header?: {
                "X-CSRF-Token"?: string | null;
            };
            path: {
                workspace_id: string;
                job_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["JobCancellationRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            202: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: string;
                    };
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    lifecycle_api_v1_workspaces__workspace_id__lifecycle_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                workspace_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["WorkspaceView"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    execute_workspace_reset_api_v1_workspaces__workspace_id__lifecycle_reset_execute_post: {
        parameters: {
            query?: never;
            header?: {
                "X-CSRF-Token"?: string | null;
            };
            path: {
                workspace_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ResetExecuteRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ResetReceiptView"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    prepare_workspace_reset_api_v1_workspaces__workspace_id__lifecycle_reset_prepare_post: {
        parameters: {
            query?: never;
            header?: {
                "X-CSRF-Token"?: string | null;
            };
            path: {
                workspace_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ResetPrepareRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ResetChallengeView"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    mode_view_api_v1_workspaces__workspace_id__modes__mode__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                workspace_id: string;
                mode: components["schemas"]["ModeName"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ModeView"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
}
