"""WP-13 Support implementation slice."""

from .errors import SupportError, SupportErrorCode
from .evaluation import (
    evaluate_commercial_readiness,
    evaluate_control,
    evaluate_id_completeness,
    evaluate_material_admission,
    evaluate_work_readiness,
)
from .generation import (
    PackageValidation,
    SyntheticOoxmlGenerationPipeline,
    validate_docx,
    validate_xlsx,
)
from .geometry import form_executive_scheme
from .models import (
    CalibrationEvidence,
    CommercialReadiness,
    CommercialReadinessInput,
    CompletenessDelta,
    ControlEvidence,
    ControlOutcome,
    ControlResult,
    DocumentCoverageEvidence,
    DocumentRequirementEvidence,
    ExecutiveSchemeResult,
    FieldResolution,
    GeneratedDocumentCandidate,
    GenerationRequest,
    GeometryInput,
    GeometryOutcome,
    MaterialAdmission,
    MaterialAdmissionResult,
    MaterialBatchEvidence,
    OfflineDisposition,
    OfflineFactEnvelope,
    OfflineReconciliation,
    ProfessionalAuthority,
    ResolutionState,
    SupportScope,
    SupportState,
    SupportTerminalResult,
    WorkReadiness,
    WorkReadinessInput,
    WorkReadinessResult,
    require_independent_authorities,
)
from .offline import OfflineFactReconciler
from .postgres import PostgresSupportProcess, StartSupportProcess
from .process import (
    SupportCommand,
    SupportCommandOutcome,
    SupportCommandType,
    SupportEvent,
    SupportProcessStateMachine,
)
from .production import (
    DocumentMembershipVersion,
    IdDocumentRequirement,
    IdPackageVersion,
    MembershipRevision,
    MembershipState,
    PackageReadinessEvaluation,
    RequirementBasis,
    RequirementState,
    TemplateBackedDocxRenderer,
    TemplateRenderResult,
    VolumeBookVersion,
    evaluate_package_readiness,
    evolve_package_version,
    registry_manifest,
)
from .production_postgres import SupportProductionError, SupportProductionRepository
from .release_readiness import (
    SupportReleaseReadiness,
    SupportReleaseReadinessService,
    load_support_work_type_profiles,
    support_writer_status,
)
from .template_postgres import OfficialTemplatePublisher, QualifiedTemplatePublication
from .template_qualification import (
    OfficialPdfFormProfile,
    PdfOverlayBinding,
    PdfOverlayRenderer,
    PdfPrintValidationReceipt,
    TemplateQualificationReceipt,
    load_official_pdf_form_profile,
    qualify_official_pdf_form,
)

__all__ = [
    "CalibrationEvidence",
    "CommercialReadiness",
    "CommercialReadinessInput",
    "CompletenessDelta",
    "ControlEvidence",
    "ControlOutcome",
    "ControlResult",
    "DocumentCoverageEvidence",
    "DocumentMembershipVersion",
    "DocumentRequirementEvidence",
    "ExecutiveSchemeResult",
    "FieldResolution",
    "GeneratedDocumentCandidate",
    "GenerationRequest",
    "GeometryInput",
    "GeometryOutcome",
    "IdDocumentRequirement",
    "IdPackageVersion",
    "MaterialAdmission",
    "MaterialAdmissionResult",
    "MaterialBatchEvidence",
    "MembershipRevision",
    "MembershipState",
    "OfficialPdfFormProfile",
    "OfficialTemplatePublisher",
    "OfflineDisposition",
    "OfflineFactEnvelope",
    "OfflineFactReconciler",
    "OfflineReconciliation",
    "PackageReadinessEvaluation",
    "PackageValidation",
    "PdfOverlayBinding",
    "PdfOverlayRenderer",
    "PdfPrintValidationReceipt",
    "PostgresSupportProcess",
    "ProfessionalAuthority",
    "QualifiedTemplatePublication",
    "RequirementBasis",
    "RequirementState",
    "ResolutionState",
    "StartSupportProcess",
    "SupportCommand",
    "SupportCommandOutcome",
    "SupportCommandType",
    "SupportError",
    "SupportErrorCode",
    "SupportEvent",
    "SupportProcessStateMachine",
    "SupportProductionError",
    "SupportProductionRepository",
    "SupportReleaseReadiness",
    "SupportReleaseReadinessService",
    "SupportScope",
    "SupportState",
    "SupportTerminalResult",
    "SyntheticOoxmlGenerationPipeline",
    "TemplateBackedDocxRenderer",
    "TemplateQualificationReceipt",
    "TemplateRenderResult",
    "VolumeBookVersion",
    "WorkReadiness",
    "WorkReadinessInput",
    "WorkReadinessResult",
    "evaluate_commercial_readiness",
    "evaluate_control",
    "evaluate_id_completeness",
    "evaluate_material_admission",
    "evaluate_package_readiness",
    "evaluate_work_readiness",
    "evolve_package_version",
    "form_executive_scheme",
    "load_official_pdf_form_profile",
    "load_support_work_type_profiles",
    "qualify_official_pdf_form",
    "registry_manifest",
    "require_independent_authorities",
    "support_writer_status",
    "validate_docx",
    "validate_xlsx",
]
