"""Typed failures for the WP-13 Support slice."""

from __future__ import annotations

from dataclasses import dataclass
from enum import StrEnum


class SupportErrorCode(StrEnum):
    INVALID_STATE = "SUPPORT_INVALID_STATE"
    CONCURRENCY_CONFLICT = "SUPPORT_CONCURRENCY_CONFLICT"
    IDEMPOTENCY_CONFLICT = "SUPPORT_IDEMPOTENCY_CONFLICT"
    AUTHORITY_DENIED = "SUPPORT_AUTHORITY_DENIED"
    WORKSPACE_FENCED = "SUPPORT_WORKSPACE_FENCED"
    EVIDENCE_MISSING = "SUPPORT_EVIDENCE_MISSING"
    PREDECESSOR_BLOCKED = "SUPPORT_PREDECESSOR_BLOCKED"
    MATERIAL_NOT_ADMITTED = "SUPPORT_MATERIAL_NOT_ADMITTED"
    CUSTODY_GAP = "SUPPORT_CUSTODY_GAP"
    CONTROL_FAILED = "SUPPORT_CONTROL_FAILED"
    CALIBRATION_INVALID = "SUPPORT_CALIBRATION_INVALID"
    DOCUMENT_INCOMPLETE = "SUPPORT_DOCUMENT_INCOMPLETE"
    GENERATION_BLOCKED = "SUPPORT_GENERATION_BLOCKED"
    TEMPLATE_NOT_QUALIFIED = "SUPPORT_TEMPLATE_NOT_QUALIFIED"
    PRINT_NOT_QUALIFIED = "SUPPORT_PRINT_NOT_QUALIFIED"
    GEOMETRY_BLOCKED = "SUPPORT_GEOMETRY_BLOCKED"
    VOLUME_EXCEEDED = "SUPPORT_VOLUME_EXCEEDED"
    PAYMENT_BLOCKED = "SUPPORT_PAYMENT_BLOCKED"
    OFFLINE_CONFLICT = "SUPPORT_OFFLINE_CONFLICT"
    SCOPE_VIOLATION = "SUPPORT_SCOPE_VIOLATION"


@dataclass(slots=True)
class SupportError(Exception):
    code: SupportErrorCode
    safe_message: str
    terminal: bool = True

    def __str__(self) -> str:
        return f"{self.code}: {self.safe_message}"
