"""WP-12 Tender slice built on the common domain process kernel."""

from .analysis import assess_corpus, product_ready, terminal_outcome_for
from .errors import TenderError, TenderErrorCode
from .models import (
    AuthorityLayer,
    ClauseProvenance,
    ContractClause,
    CorpusAssessment,
    CorpusItem,
    DisagreementItem,
    LegalAuthority,
    RevisedClause,
    RiskSubject,
    Severity,
    SourceClass,
    TenderDeliverableKind,
    TenderFinalizationDecision,
    TenderIssue,
    TenderIssueKind,
    TenderRequirement,
    TenderScope,
    TenderState,
    TenderStep,
    TenderTerminalOutcome,
    TypedTenderDeliverable,
)
from .postgres import (
    ALLOWED_TRANSITIONS,
    PostgresTenderProcess,
    StartTenderCommand,
    TenderProcessResult,
    TransitionTenderCommand,
)
from .validators import (
    TenderValidationCode,
    TenderValidationFailure,
    TenderValidationInput,
    validate_tender,
)

__all__ = [
    "ALLOWED_TRANSITIONS",
    "AuthorityLayer",
    "ClauseProvenance",
    "ContractClause",
    "CorpusAssessment",
    "CorpusItem",
    "DisagreementItem",
    "LegalAuthority",
    "PostgresTenderProcess",
    "RevisedClause",
    "RiskSubject",
    "Severity",
    "SourceClass",
    "StartTenderCommand",
    "TenderDeliverableKind",
    "TenderError",
    "TenderErrorCode",
    "TenderFinalizationDecision",
    "TenderIssue",
    "TenderIssueKind",
    "TenderProcessResult",
    "TenderRequirement",
    "TenderScope",
    "TenderState",
    "TenderStep",
    "TenderTerminalOutcome",
    "TenderValidationCode",
    "TenderValidationFailure",
    "TenderValidationInput",
    "TransitionTenderCommand",
    "TypedTenderDeliverable",
    "assess_corpus",
    "product_ready",
    "terminal_outcome_for",
    "validate_tender",
]
