"""Small project-independent vocabulary for professional Tender findings."""

from __future__ import annotations

from enum import StrEnum


class ProfessionalFindingKind(StrEnum):
    QUANTITY_MISMATCH = "QUANTITY_MISMATCH"
    COMPONENT_TOTAL_MISMATCH = "COMPONENT_TOTAL_MISMATCH"
    MATERIAL_MISMATCH = "MATERIAL_MISMATCH"
    GEOMETRY_MISMATCH = "GEOMETRY_MISMATCH"
    DURATION_MISMATCH = "DURATION_MISMATCH"
    REVISION_CONFLICT = "REVISION_CONFLICT"
    DESIGN_SCOPE_MISSING_COMMERCIAL = "DESIGN_SCOPE_MISSING_COMMERCIAL"
    COMMERCIAL_SCOPE_WITHOUT_DESIGN_BASIS = "COMMERCIAL_SCOPE_WITHOUT_DESIGN_BASIS"
    MISSING_PROJECT_INFORMATION = "MISSING_PROJECT_INFORMATION"
    NTD_NONCOMPLIANCE = "NTD_NONCOMPLIANCE"
    NTD_APPLICABILITY_UNRESOLVED = "NTD_APPLICABILITY_UNRESOLVED"
    CONTRACT_RISK = "CONTRACT_RISK"
    PROCUREMENT_RISK = "PROCUREMENT_RISK"
    CONSTRUCTABILITY_RISK = "CONSTRUCTABILITY_RISK"
    OTHER_ENGINEERING_CONFLICT = "OTHER_ENGINEERING_CONFLICT"
