"""Platform methodological-practice-guide ingestion and retrieval."""

from .context import (
    IDPracticeContextAssembler,
    IDPracticeContextRequest,
    IDRelatedVlmContextGate,
    PreparedIDVlmContext,
)
from .memory_backup import (
    build_backup_manifest,
    canonical_semantic_fingerprint,
    verify_restored_practice_memory,
)
from .models import (
    ContextAssemblyPolicy,
    GuidanceCandidateVersion,
    GuidanceConflict,
    GuidanceCuratorAuthority,
    GuidanceKind,
    GuidanceUncertainty,
    GuidanceVerification,
    GuideAuthorityLayer,
    GuideContentKind,
    GuideExecutionProfile,
    GuideLocator,
    GuidePageManifest,
    GuidePageTerminalReceipt,
    GuideTerminalState,
    IDPracticeContextPack,
    IDPracticeIntelligenceUnit,
    PracticeContextStatus,
    PracticeGuideEditionActivationDecision,
    PracticeIntelligenceEvidence,
    PracticeIntelligenceKind,
    PracticeMemoryBackupManifest,
    PracticePlaybook,
    VerificationDisposition,
    reconcile_page_receipts,
)

__all__ = [
    "ContextAssemblyPolicy",
    "GuidanceCandidateVersion",
    "GuidanceConflict",
    "GuidanceCuratorAuthority",
    "GuidanceKind",
    "GuidanceUncertainty",
    "GuidanceVerification",
    "GuideAuthorityLayer",
    "GuideContentKind",
    "GuideExecutionProfile",
    "GuideLocator",
    "GuidePageManifest",
    "GuidePageTerminalReceipt",
    "GuideTerminalState",
    "IDPracticeContextAssembler",
    "IDPracticeContextPack",
    "IDPracticeContextRequest",
    "IDPracticeIntelligenceUnit",
    "IDRelatedVlmContextGate",
    "PracticeContextStatus",
    "PracticeGuideEditionActivationDecision",
    "PracticeIntelligenceEvidence",
    "PracticeIntelligenceKind",
    "PracticeMemoryBackupManifest",
    "PracticePlaybook",
    "PreparedIDVlmContext",
    "VerificationDisposition",
    "build_backup_manifest",
    "canonical_semantic_fingerprint",
    "reconcile_page_receipts",
    "verify_restored_practice_memory",
]
